name: sast-dependency-check

on:
  workflow_call:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check (CLI only)
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.5/dependency-check-8.4.5-release.zip
          unzip dependency-check.zip -d dc
          cd dc/dependency-check
          ./bin/dependency-check.sh --format CLI --failOnCVSS 6.5 --scan $GITHUB_WORKSPACE